name: mcPlugin2
version: '${version}'

main: org.plugin2.mcplugin2.McPlugin2
api-version: '1.21.5'
load: POSTWORLD
commands:
  setGameLoc:
    description: sets the location of a a game with the given id
    permission: chess.admin
    usage: /setgameloc <number>
  setMaxGames:
    description: sets the max possible amount of games
    permission: chess.admin
    usage: /setmaxgames <number>
  duel:
    description: sents a duel request to a player
    usage: /duel <player>
  acceptDuel:
    description: accept a duel
    usage: /acceptDuel <player>
  setChessSpawn:
    description: sents the spawn where players will be tped to after a match is over
    permission: chess.admin
    usage: /setChessSpawn